// Kapitel9/example-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  users = [
    {
      firstName: 'Max',
      lastName: 'Mustermann'
    },
    {
      firstName: 'Moritz',
      lastName: 'Mustermann'
    },
    {
      firstName: 'Peter',
      lastName: 'Mustermann'
    },
    {
      firstName: 'Petra',
      lastName: 'Mustermann'
    }
  ];
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<p>Users:</p>
  <ul>
    <li *ngFor="let user of users">
      {{ user.firstName }} {{ user.lastName }}
    </li>
</ul>

// Kapitel9/example-react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

function UserList(props) {
  const users = props.users;
  const listItems = users.map((user) =>
    <li>
      {user.firstName} {user.lastName}
    </li>
  );
  return (
    <ul>{listItems}</ul>
  );
}
  
const users = [
  {
    firstName: 'Max',
    lastName: 'Mustermann'
  },
  {
    firstName: 'Moritz',
    lastName: 'Mustermann'
  },
  {
    firstName: 'Peter',
    lastName: 'Mustermann'
  },
  {
    firstName: 'Petra',
    lastName: 'Mustermann'
  }
];

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
        <UserList users={users} />
        </p>
      </div>
    );
  }
}

export default App;
